name: Publish PR Version

on:
  pull_request:
    types: [labeled]

jobs:
  publish-pr:
    runs-on: ubuntu-latest

    if: github.event.label.name == 'Publish PR Version'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: publish to npm
        run: |
          npm version "0.0.0-PR-${PR}--${SHA}" --no-git-tag-version
          npm publish --access public --tag pr
        env:
          PR: ${{ github.event.number }}
          SHA: ${{ github.event.pull_request.head.sha }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cat ./.npmrc
